// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace TaleworldsCodeAnalysis.Controller
{
    internal sealed partial class Vsix
    {
        public const string Id = "TaleworldsCodeAnalysis.Controller.90a0ba77-7c1d-4576-9636-20acb555acaf";
        public const string Name = "TaleworldsCodeAnalysis.Controller";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "BERKAY KARAKAYA";
        public const string Tags = "";
    }
}
