// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the free extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
using System;

namespace TaleworldsCodeAnalysis.Controller
{
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string TaleworldsCodeAnalysisControllerString = "bb14e7f4-1f15-4413-b903-3c38e1df9ecc";
        public static Guid TaleworldsCodeAnalysisController = new Guid(TaleworldsCodeAnalysisControllerString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyCommand = 0x0100;
    }
}