//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaleworldsCodeAnalysis.OtherCheckers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OtherCheckerResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OtherCheckerResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TaleworldsCodeAnalysis.OtherCheckers.OtherCheckerResource", typeof(OtherCheckerResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Structs that has only one field should be immutable (Place readonly modifier on the field).
        /// </summary>
        internal static string ImmutableStructCheckerMessage {
            get {
                return ResourceManager.GetString("ImmutableStructCheckerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This struct should be immutable.
        /// </summary>
        internal static string ImmutableStructCheckerTitle {
            get {
                return ResourceManager.GetString("ImmutableStructCheckerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access modifier should not be mixed..
        /// </summary>
        internal static string MixedAccessModifierCheckerMessage {
            get {
                return ResourceManager.GetString("MixedAccessModifierCheckerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access modifier should not be mixed..
        /// </summary>
        internal static string MixedAccessModifierCheckerTitle {
            get {
                return ResourceManager.GetString("MixedAccessModifierCheckerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should not return a &quot;List&quot; that is a field. It can be modified outside.
        /// </summary>
        internal static string MutableFieldReturnCheckerMessage {
            get {
                return ResourceManager.GetString("MutableFieldReturnCheckerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should not return a &quot;List&quot; that is a field. It can be modified outside.
        /// </summary>
        internal static string MutableFieldReturnCheckerTitle {
            get {
                return ResourceManager.GetString("MutableFieldReturnCheckerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to call method with its parameter names if it has more than .
        /// </summary>
        internal static string NamedParameterCheckerMessage {
            get {
                return ResourceManager.GetString("NamedParameterCheckerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to call method with its parameter names if it has more than .
        /// </summary>
        internal static string NamedParameterCheckerTitle {
            get {
                return ResourceManager.GetString("NamedParameterCheckerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can use var instead of {0}.
        /// </summary>
        internal static string VarKeywordCheckerMessage {
            get {
                return ResourceManager.GetString("VarKeywordCheckerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can use var instead of {0}.
        /// </summary>
        internal static string VarKeywordCheckerTitle {
            get {
                return ResourceManager.GetString("VarKeywordCheckerTitle", resourceCulture);
            }
        }
    }
}
